;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-insert-left-brace
	TeX-insert-backslash
	backward-sexp
	beginning-of-visual-line
	c-electric-paren
	c-electric-slash
	copy-rectangle-as-kill
	electric-newline-and-maybe-indent
	electric-pair-delete-pair
	electric-verilog-tab
	elpy-nav-indent-shift-left
	elpy-shell-send-region-or-buffer
	end-of-defun
	end-of-visual-line
	eval-last-sexp
	forward-sexp
	hungry-delete-backward
	hungry-delete-forward
	indent-for-tab-command
	indent-new-comment-line
	kill-region
	kill-visual-line
	org-force-self-insert
	org-metaleft
	org-metaright
	org-return-indent
	org-self-insert-command
	yank-rectangle
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	counsel-M-x
	counsel-describe-function
	end-of-buffer
	eval-print-last-sexp
	handle-switch-frame
	ido-switch-buffer
	iedit-switch-to-mc-mode
	ignore
	keyboard-escape-quit
	org-export-dispatch
	outline-previous-visible-heading
	plantuml-preview
	text-scale-adjust
	verilog-expand-vector
	))
